### ISSUE TITLE
Autoload problem

### ISSUE THREAD

**Issue by lulco** [deprecated-packages/reveal#3]
Is there some description how to use this package? After installing via composer I've got some autoload problems:
```
Service (Reveal\TemplatePHPStanCompiler\PHPStan\FileAnalyserProvider::__construct()): Class 'Reveal\TemplatePHPStanCompiler\PHPStan\FileAnalyserProvider' not found.
```

I had to run phpstan with option `--autoload-file vendor/reveal/reveal/vendor/autoload.php`. Is it correct?

**Comment by TomasVotruba** [comment]
My rought guess... It might require to add `scoper-autolad.php` to `bin/reveal.php`.
